var annotated_dup =
[
    [ "PurePursuit", null, [
      [ "hermite_point", "structPurePursuit_1_1hermite__point.html", null ],
      [ "Path", "classPurePursuit_1_1Path.html", "classPurePursuit_1_1Path" ],
      [ "spline", "structPurePursuit_1_1spline.html", null ]
    ] ],
    [ "screen", null, [
      [ "ButtonWidget", "classscreen_1_1ButtonWidget.html", "classscreen_1_1ButtonWidget" ],
      [ "FunctionPage", "classscreen_1_1FunctionPage.html", "classscreen_1_1FunctionPage" ],
      [ "OdometryPage", "classscreen_1_1OdometryPage.html", "classscreen_1_1OdometryPage" ],
      [ "Page", "classscreen_1_1Page.html", "classscreen_1_1Page" ],
      [ "PIDPage", "classscreen_1_1PIDPage.html", "classscreen_1_1PIDPage" ],
      [ "ScreenData", "structscreen_1_1ScreenData.html", null ],
      [ "SliderWidget", "classscreen_1_1SliderWidget.html", "classscreen_1_1SliderWidget" ],
      [ "StatsPage", "classscreen_1_1StatsPage.html", "classscreen_1_1StatsPage" ]
    ] ],
    [ "Async", "classAsync.html", null ],
    [ "AutoChooser", "classAutoChooser.html", "classAutoChooser" ],
    [ "BasicSolenoidSet", "classBasicSolenoidSet.html", "classBasicSolenoidSet" ],
    [ "BasicSpinCommand", "classBasicSpinCommand.html", "classBasicSpinCommand" ],
    [ "BasicStopCommand", "classBasicStopCommand.html", "classBasicStopCommand" ],
    [ "Branch", "classBranch.html", null ],
    [ "CommandController", "classCommandController.html", "classCommandController" ],
    [ "Condition", "classCondition.html", null ],
    [ "CustomEncoder", "classCustomEncoder.html", "classCustomEncoder" ],
    [ "DelayCommand", "classDelayCommand.html", "classDelayCommand" ],
    [ "DriveForwardCommand", "classDriveForwardCommand.html", "classDriveForwardCommand" ],
    [ "DriveStopCommand", "classDriveStopCommand.html", "classDriveStopCommand" ],
    [ "DriveToPointCommand", "classDriveToPointCommand.html", "classDriveToPointCommand" ],
    [ "ExponentialMovingAverage", "classExponentialMovingAverage.html", "classExponentialMovingAverage" ],
    [ "Feedback", "classFeedback.html", "classFeedback" ],
    [ "FeedForward", "classFeedForward.html", "classFeedForward" ],
    [ "Filter", "classFilter.html", null ],
    [ "Flywheel", "classFlywheel.html", "classFlywheel" ],
    [ "FlywheelStopCommand", "classFlywheelStopCommand.html", "classFlywheelStopCommand" ],
    [ "FlywheelStopMotorsCommand", "classFlywheelStopMotorsCommand.html", "classFlywheelStopMotorsCommand" ],
    [ "FlywheelStopNonTasksCommand", "classFlywheelStopNonTasksCommand.html", null ],
    [ "FunctionCommand", "classFunctionCommand.html", null ],
    [ "FunctionCondition", "classFunctionCondition.html", null ],
    [ "GenericAuto", "classGenericAuto.html", "classGenericAuto" ],
    [ "IfTimePassed", "classIfTimePassed.html", null ],
    [ "InOrder", "classInOrder.html", null ],
    [ "Lift", "classLift.html", "classLift" ],
    [ "Logger", "classLogger.html", "classLogger" ],
    [ "MecanumDrive", "classMecanumDrive.html", "classMecanumDrive" ],
    [ "motion_t", "structmotion__t.html", "structmotion__t" ],
    [ "MotionController", "classMotionController.html", "classMotionController" ],
    [ "MovingAverage", "classMovingAverage.html", "classMovingAverage" ],
    [ "Odometry3Wheel", "classOdometry3Wheel.html", "classOdometry3Wheel" ],
    [ "OdometryBase", "classOdometryBase.html", "classOdometryBase" ],
    [ "OdometryTank", "classOdometryTank.html", "classOdometryTank" ],
    [ "OdomSetPosition", "classOdomSetPosition.html", "classOdomSetPosition" ],
    [ "Parallel", "classParallel.html", null ],
    [ "PID", "classPID.html", "classPID" ],
    [ "point_t", "structpoint__t.html", "structpoint__t" ],
    [ "Pose2d", "classPose2d.html", "classPose2d" ],
    [ "pose_t", "structpose__t.html", "structpose__t" ],
    [ "PurePursuitCommand", "classPurePursuitCommand.html", "classPurePursuitCommand" ],
    [ "robot_specs_t", "structrobot__specs__t.html", "structrobot__specs__t" ],
    [ "Rotation2d", "classRotation2d.html", "classRotation2d" ],
    [ "Serializer", "classSerializer.html", "classSerializer" ],
    [ "SpinRPMCommand", "classSpinRPMCommand.html", "classSpinRPMCommand" ],
    [ "StateMachine", "classStateMachine.html", "classStateMachine" ],
    [ "TakeBackHalf", "classTakeBackHalf.html", "classTakeBackHalf" ],
    [ "TankDrive", "classTankDrive.html", "classTankDrive" ],
    [ "tracking_wheel_cfg_t", "structtracking__wheel__cfg__t.html", "structtracking__wheel__cfg__t" ],
    [ "Transform2d", "classTransform2d.html", "classTransform2d" ],
    [ "Translation2d", "classTranslation2d.html", "classTranslation2d" ],
    [ "TrapezoidProfile", "classTrapezoidProfile.html", "classTrapezoidProfile" ],
    [ "TurnDegreesCommand", "classTurnDegreesCommand.html", "classTurnDegreesCommand" ],
    [ "TurnToHeadingCommand", "classTurnToHeadingCommand.html", "classTurnToHeadingCommand" ],
    [ "Twist2d", "classTwist2d.html", "classTwist2d" ],
    [ "Vector2D", "classVector2D.html", "classVector2D" ],
    [ "WaitUntilCondition", "classWaitUntilCondition.html", null ],
    [ "WaitUntilUpToSpeedCommand", "classWaitUntilUpToSpeedCommand.html", "classWaitUntilUpToSpeedCommand" ]
];