var annotated_dup =
[
    [ "PurePursuit", null, [
      [ "hermite_point", "structPurePursuit_1_1hermite__point.html", null ],
      [ "spline", "structPurePursuit_1_1spline.html", null ]
    ] ],
    [ "screen", null, [
      [ "FunctionPage", "classscreen_1_1FunctionPage.html", "classscreen_1_1FunctionPage" ],
      [ "OdometryPage", "classscreen_1_1OdometryPage.html", "classscreen_1_1OdometryPage" ],
      [ "Page", "classscreen_1_1Page.html", "classscreen_1_1Page" ],
      [ "ScreenData", "structscreen_1_1ScreenData.html", null ],
      [ "StatsPage", "classscreen_1_1StatsPage.html", "classscreen_1_1StatsPage" ]
    ] ],
    [ "Async", "classAsync.html", "classAsync" ],
    [ "AutoChooser", "classAutoChooser.html", "classAutoChooser" ],
    [ "AutoCommand", "classAutoCommand.html", "classAutoCommand" ],
    [ "Branch", "classBranch.html", "classBranch" ],
    [ "CommandController", "classCommandController.html", "classCommandController" ],
    [ "Condition", "classCondition.html", null ],
    [ "CustomEncoder", "classCustomEncoder.html", "classCustomEncoder" ],
    [ "DelayCommand", "classDelayCommand.html", "classDelayCommand" ],
    [ "DriveForwardCommand", "classDriveForwardCommand.html", "classDriveForwardCommand" ],
    [ "DriveStopCommand", "classDriveStopCommand.html", "classDriveStopCommand" ],
    [ "DriveToPointCommand", "classDriveToPointCommand.html", "classDriveToPointCommand" ],
    [ "Feedback", "classFeedback.html", "classFeedback" ],
    [ "FeedForward", "classFeedForward.html", "classFeedForward" ],
    [ "Flywheel", "classFlywheel.html", "classFlywheel" ],
    [ "FlywheelStopCommand", "classFlywheelStopCommand.html", "classFlywheelStopCommand" ],
    [ "FlywheelStopMotorsCommand", "classFlywheelStopMotorsCommand.html", "classFlywheelStopMotorsCommand" ],
    [ "FlywheelStopNonTasksCommand", "classFlywheelStopNonTasksCommand.html", null ],
    [ "FunctionCommand", "classFunctionCommand.html", "classFunctionCommand" ],
    [ "FunctionCondition", "classFunctionCondition.html", null ],
    [ "GenericAuto", "classGenericAuto.html", "classGenericAuto" ],
    [ "GraphDrawer", "classGraphDrawer.html", "classGraphDrawer" ],
    [ "IfTimePassed", "classIfTimePassed.html", null ],
    [ "InOrder", "classInOrder.html", "classInOrder" ],
    [ "Lift", "classLift.html", "classLift" ],
    [ "Logger", "classLogger.html", "classLogger" ],
    [ "Mat2", "structMat2.html", null ],
    [ "MecanumDrive", "classMecanumDrive.html", "classMecanumDrive" ],
    [ "motion_t", "structmotion__t.html", "structmotion__t" ],
    [ "MotionController", "classMotionController.html", "classMotionController" ],
    [ "MovingAverage", "classMovingAverage.html", "classMovingAverage" ],
    [ "Odometry3Wheel", "classOdometry3Wheel.html", "classOdometry3Wheel" ],
    [ "OdometryBase", "classOdometryBase.html", "classOdometryBase" ],
    [ "OdometryTank", "classOdometryTank.html", "classOdometryTank" ],
    [ "OdomSetPosition", "classOdomSetPosition.html", "classOdomSetPosition" ],
    [ "Parallel", "classParallel.html", "classParallel" ],
    [ "parallel_runner_info", "structparallel__runner__info.html", null ],
    [ "PID", "classPID.html", "classPID" ],
    [ "PIDFF", "classPIDFF.html", "classPIDFF" ],
    [ "point_t", "structpoint__t.html", "structpoint__t" ],
    [ "pose_t", "structpose__t.html", "structpose__t" ],
    [ "PurePursuitCommand", "classPurePursuitCommand.html", "classPurePursuitCommand" ],
    [ "robot_specs_t", "structrobot__specs__t.html", "structrobot__specs__t" ],
    [ "Serializer", "classSerializer.html", "classSerializer" ],
    [ "SpinRPMCommand", "classSpinRPMCommand.html", "classSpinRPMCommand" ],
    [ "TankDrive", "classTankDrive.html", "classTankDrive" ],
    [ "TrapezoidProfile", "classTrapezoidProfile.html", "classTrapezoidProfile" ],
    [ "TurnDegreesCommand", "classTurnDegreesCommand.html", "classTurnDegreesCommand" ],
    [ "TurnToHeadingCommand", "classTurnToHeadingCommand.html", "classTurnToHeadingCommand" ],
    [ "Vector2D", "classVector2D.html", "classVector2D" ],
    [ "WaitUntilCondition", "classWaitUntilCondition.html", "classWaitUntilCondition" ],
    [ "WaitUntilUpToSpeedCommand", "classWaitUntilUpToSpeedCommand.html", "classWaitUntilUpToSpeedCommand" ]
];