name: Doxygen Action

on: 
  push:
  workflow_dispatch:
  pull_request:
    branches:
      - '*'
  
jobs:
  build:
    strategy:
      matrix:
        os: [ubuntu-latest, windows-latest, macos-latest]
    runs-on: ${{ matrix.os }}
    steps:
      - name: Checkout
        uses: actions/checkout@v4
    
  Doxygen-Action:
    needs: build
    runs-on: ubuntu-latest
    steps:
    - name: Checkout
      uses: actions/checkout@v4
    - name: Run Doxygen
      uses: mattnotmitt/doxygen-action@edge
      with:
        doxyfile-path: "./Doxyfile"
        working-directory: "."

  Generate-Reference-Manual:
    needs: Doxygen-Action
    runs-on: ubuntu-latest
    steps:
    - name: Checkout
    - uses actions/checkout@v4
    - name: Create Latex Manual
      run: sudo make --directory=documentation/latex
    - name: Copy Manual PDF
      run: cp documentation/latex/refman.pdf documentation/html/refman.pdf
    - name: Copy Manual Log
      run: cp documentation/latex/refman.log documentation/html/refman.log

  Deploy-Pages:
    needs: Generate-Reference-Manual
    permissions:
      pages: write
      id-token: write
    environment:
      name: github-pages
      url: ${{ steps.deployment.output.page_url }}
    runs-on: ${{ matrix.os }}
    steps:
      - name: Deplay to GitHub pages
        id: deployment
        uses: actions/deploy-pages@edge
